### ISSUE TITLE
Add Build Instructions

### ISSUE THREAD

**Issue by makefu** [JeremyARussell/Evolution-Game#1]
Hi, i wanted to check out the game but because i am not too familar with the whole visual studio stuff i do not know how to actually build the game. I tried to grab a compiled copy from http://www.thegameofevolution.com/downloads/ but your website seems to be down.

I am not sure how hard it is to make it build on linux but it surely would be a cool thing.

Cheers

**Comment by JeremyARussell** [comment]
If you're running Windows and haven't used Visual Studio before it's not too hard to get it going. You just install Visual Studio (currently located at https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx) with the C++ option enabled and then open up the .sln file mentioned in the readme. From there you just select if you're building a debug or release build (see the following image, the spot labelled A) then hit the "play" aka build button (as seen at label B). [Said Image](http://imgur.com/mlcu3uD)

As far as the site goes where did you grab that link? I'm thinking maybe twitter off the top of my head.. In any case the site is in fact down and has been for awhile so you have to compile it until I find somewhere to host it for free.. I'm pretty sure github allows for that so I'll look into it..

It would be pretty sweet to get it setup to build in linux I'll make a note to look into it (though if you figure it out first be sure to let me know).

**Comment by kashalls** [comment]
If needed, I can create a video on how to compile. That would be good, right Jeremy?

**Comment by makefu** [comment]
@JeremyARussell thanks very much for the insight. i will check virtualstudio to build an executable.
I got the link via ... googling and arriving on the twitter account (coming originally from google+). i saw there were dropbox links as well but it seemed to be down as well :)

On github you can even host built releases ( binaries ) quite easily. maybe this would be a fast way to share it with the world.

@Altaris9 please no "Instruction Videos" :D just write down what needs to be done, really.

**Comment by JeremyARussell** [comment]
I think it's safe to close this, Visual Studio is fairly straight forward in opening and compiling solutions, I'll probably add the binaries as a release during the next big update to let people easily play the game.

**Comment by makefu** [comment]
2016, wow :D
thanks for the follow-up
